FROM debian:jessie
MAINTAINER ola.angelsmark@ericsson.com
ARG branch=master
#proxy settings
ENV http_proxy=http://proxy.rd.francetelecom.fr:8080
ENV FTP_PROXY=http://proxy.rd.francetelecom.fr:8080
ENV ftp_proxy=http://proxy.rd.francetelecom.fr:8080
ENV https_proxy=http://proxy.rd.francetelecom.fr:8080
ENV HTTPS_PROXY=http://proxy.rd.francetelecom.fr:8080
ENV no_proxy=localhost,125.0.0.1,10.193.0.0,10.194.0.0,.francetelecom.fr,192.168.0.100,127.0.0.1
ENV HTTP_PROXY=http://proxy.rd.francetelecom.fr:8080

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       gcc g++ python2.7 python-dev libffi-dev libssl-dev python-smbus wget ca-certificates git \
       python-pygame python-opencv\
    && rm -rf /var/lib/apt/lists/* \
    && wget https://bootstrap.pypa.io/get-pip.py -O - | python \
    && pip install requests \
    && git clone -b $branch https://github.com/EricssonResearch/calvin-base calvin-base \
    && cd /calvin-base \
    && pip install --upgrade -r requirements.txt -r test-requirements.txt -e .
WORKDIR /calvin-base

EXPOSE 5000 5001
